version: "3.7"

x-kong-config:
  &kong-env
  KONG_DATABASE: postgres
  KONG_PG_DATABASE: kong
  KONG_PG_HOST: postgres
  KONG_PG_USER: kong
  KONG_PG_PASSWORD: kong

services:
  postgres:
    image: postgres:9.5
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong

  kong-migrations:
    image: kong:3.7.0
    container_name: kong-migrations
    command: kong migrations bootstrap
    environment:
      <<: *kong-env
    networks:
      - kong
    depends_on:
      - postgres

  kong-migrations-up:
    image: kong:3.7.0
    container_name: kong-migrations-up
    command: kong migrations up && kong migrations finish
    environment:
      <<: *kong-env
    networks:
      - kong
    depends_on:
      - kong-migrations
      - postgres

  kong-db-import:
    image: kong:3.7.0
    container_name: kong-db-import
    command: kong config db_import /etc/kong/kong.yml
    environment:
      <<: *kong-env
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    networks:
      - kong
    depends_on:
      - kong-migrations-up
      - postgres

  kong:
    image: kong:3.7.0
    container_name: kong
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    environment:
      <<: *kong-env
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    networks:
      - kong
      - microservices
    depends_on:
      - kong-db-import
      - postgres

  konga:
    image: pantsel/konga:latest
    container_name: konga
    ports:
      - "8002:1337"
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgres://kong:kong@postgres:5432/konga
    networks:
      - kong
      - microservices

networks:
  kong:
    driver: bridge
  microservices:
    driver: bridge
